fix: always show native assets regardless of denoms
stationmoney/station pull request #348
Opened 2023-04-19 18:23 UTC by ericHgorski

2023-04-19 18:24 UTC, ericHgorski commented
If this looks good, Ill make same change on extension

2023-04-19 18:24 UTC, ericHgorski commented on src/utils/chain.ts
> +export const isNativeToken = (denom: string) => !denom.startsWith("ibc/")
Is this robust @alecande11 ?

2023-04-24 15:09 UTC, alecande11 requested changes

2023-04-24 15:09 UTC, alecande11 commented on src/utils/chain.ts
> +export const isNativeToken = (denom: string) => !denom.startsWith("ibc/")
I think now that we have the token factory module, we should also check if the denom starts with `factory/`

2023-05-03 10:48 UTC, alecande11 approved these changes

2023-05-11 15:19 UTC, mwmerz approved these changes

2023-05-11 15:22 UTC, mwmerz approved these changes

2023-05-11 15:27 UTC, merged