feat: factory token names
stationmoney/station pull request #378
Opened 2023-05-11 19:19 UTC by terran6

2023-05-12 18:56 UTC, mwmerz commented on src/data/token.tsx
> +      ? denom.split("/").pop()?.slice(1).toUpperCase()
This is the right idea.  Unfortunately there is no standard for what happens after "factory".

For example, on osmosis, there are several factory tokens for compounding vaults.  Their denom string is:
`factory/osmo1g3kmqpp8608szfp0pdag3r6z85npph7wmccat8lgl3mp407kv73qlj7qwp/VaultToken/1/14d/ATOM/OSMO`

While this conforms to its own standard, it illustrates that almost anything can come after `factory/`

2023-05-26 16:33 UTC, mwmerz approved these changes

2023-05-29 15:17 UTC, alecande11 requested changes

2023-05-29 15:17 UTC, alecande11 commented on src/data/external/osmosis.ts
> +  "https://raw.githubusercontent.com/terra-money/station-assets/main/img/chains/Osmosis.svg"
I would use this image link here: https://station-assets.terra.money/img/chains/Osmosis.svg
It's the same image but from the deployed URL

2023-05-29 15:47 UTC, merged

2023-05-29 15:47 UTC, alecande11 approved these changes