Add QR code to connected wallet pop-up
stationmoney/station pull request #45
Opened 2022-03-12 08:14 UTC by rafaelzimmermann

This make it easier to read the connected wallet address from another
device by using a QRCode reader.

It is common to have an exchange wallet on your phone and the station on your desktop. This will make it easier to read the station wallet connected address into my phone while making a deposit.

2022-03-12 08:29 UTC, dricazenck approved these changes

2022-03-12 09:23 UTC, simcheolhwan commented
Thanks for this commit. 

This feature was already planned to be implemented. The Terra Station extension already has this function, so can you make it use the same module? Refer to the link below. Or I can do it myself.

https://github.com/terra-money/station-extension/blob/main/src/extension/components/WalletQR.tsx

2022-03-12 10:08 UTC, rafaelzimmermann commented
Thanks! If you don't mind, I would like to do it 😄

2022-03-12 15:09 UTC, rafaelzimmermann commented
@simcheolhwan I updated the PR

2022-03-13 08:59 UTC, simcheolhwan requested changes

2022-03-13 08:59 UTC, simcheolhwan commented on src/app/sections/Connected.module.scss
> +button {
This will affect all buttons in the application.

2022-03-13 10:50 UTC, merged

2022-03-13 10:58 UTC, simcheolhwan commented
c58f3e5 
I couldn't explain everything, so I added some changes to your code.
This is what I wanted.